version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: minio
    ports:
      - 9000:9000
      - 8082:8082
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "
      mkdir -p /data/testing;
      /usr/bin/docker-entrypoint.sh server --console-address 0.0.0.0:8082 /data;"
    volumes:
      - ./docker/data/minio:/data
